---
title: "Assig3"
author: "Juan Carlos Villaseñor-Derbez"
date: "22 de febrero de 2017"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(readr)
  library(tidyverse)
  library(reshape)
  library(popbio)
})
```

## Load the data

```{r}
load("size.RData") #This is the entire data, loads it into a data.frame called size
```


##

```{r}
# Define Von Bert parameters
# Garbin & Castello, 2014
# L_inf <- mean(c(80, 80, 87.12, 94, 97.9, 97.3, 112.34, 89.38, 92.5))
K <- mean(c(0.32, 0.6, 0.22, 0.38, 0.14, 0.25, 0.14, 0.38, 0.16))

# Or from Us and Stiurskjgfas, 1981
L_inf <- 102
# K <- 0.55
t_0 <- 0.02

# Just to be clear, we use L-inf  and to from Ushisomething, and K from the review

# Define fecundity parameters
# From fishbase http://www.fishbase.se/Reproduction/FecundityList.php?ID=107&GenusName=Katsuwonus&SpeciesName=pelamis&fc=416&StockCode=121
fec_a <- -1.33354
fec_b <- 3.238
# Define mortality

m <- 0.63
z <- 1.7
```

```{r}
# Define the functions we need

# Convert length to age using von bertalanffy model, solving for t
length2age <- function(length, l_inf, K, t_o){
  age <- (1/-K)*(log(1-(length/L_inf))) + t_o
  return(age)
}

# Convert age to length using von bertalanffy model
age2length <- function(age, l_inf, K, t_o){
  length <- l_inf*(1-exp(-K*(age-t_o)))
  return(length)
}

#Convert length to fecundity (number of eggs)
fecundity <- function(length, a, b){
  f <- 10^(a+(b*log10(length*10)))
  return(f)
}
```

## Check population size by cohorts through time

```{r}
size %>%
  mutate(Age = round(length2age(ClassFrq, L_inf, K, t_0))) %>%
  group_by(YearC, Age) %>%
  summarize(N = sum(as.numeric(Nr))) %>% 
  mutate(Age = as.factor(Age)) %>% 
  ungroup() %>% 
  ggplot(aes(x = YearC, y = log(N), color = Age)) +
  geom_point() +
  geom_line() +
  theme_bw() +
  labs(x = "Year", y = "log N")
```

## Build a vector with 13 age classes

```{r}
load("size_dist_1980.RData") #This is the n-vector for 1980, loads it to a vector called n

n <- n %>% {
  .$N}%>% 
  c(rep(0, times = 8))
```

## Build a 14 by 14 matrix

```{r}
A <- matrix(0, 14, 14) #initial empty matrix with all 0

# Populate matrix with mortality
for (i in 2:14){
  A[i,i-1] <- 1-m
}

# Populate matrix with fecundity
ages <- seq(0:13)-1
lengths <- age2length(ages, L_inf, K, t_0)
A[1,] <- fecundity(lengths, fec_a, fec_b)

A[is.na(A)] <- 0
A[2,1] <- 0.00001

colnames(A) <- ages
rownames(A) <- ages

knitr::kable(A)
```

## Use the total fecundity to populate our age0 class

```{r}

n_0 <- sum(A[1, 2:14]*n)

n <- c(n_0, n)

```


## Project the population

```{r}
project <- popbio::pop.projection(A, n, 30)
stage.vector.plot(project$stage.vectors, proportions = F)
```

